[project]
name = "ai-engineering"
version = "0.1.0"
description = ""
authors = [
    {name = "Kunal Mandalia",email = "kunal.v.mandalia@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter (>=1.1.1,<2.0.0)",
    "ipykernel (>=6.29.5,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
